# Generated by Django 6.0.6 on 2026-06-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('store_owner', 'Store Owner')], max_length=20),
        ),
    ]
