# Generated by Django 6.0.6 on 2026-06-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='store_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_faculty_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
