# Generated by Django 6.0.6 on 2026-06-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_passwordresetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('store_owner', 'Store Owner'), ('admin', 'Admin')], max_length=20),
        ),
    ]
