# Generated by Django 6.0.6 on 2026-06-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dti_permit',
            field=models.ImageField(blank=True, null=True, upload_to='dti_permits/'),
        ),
    ]
