# Generated by Django 6.0.6 on 2026-06-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_user_dti_permit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_image',
            field=models.ImageField(blank=True, null=True, upload_to='id_images/'),
        ),
    ]
