# Generated by Django 6.0.6 on 2026-06-09 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_user_id_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_image',
        ),
    ]
