# Generated by Django 6.0.6 on 2026-06-09 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('customer', '0008_remove_user_id_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'Order Received'), ('preparing', 'Preparing'), ('ready_for_pickup', 'Ready for Pick-Up'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='received', max_length=20),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='user',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('store_owner', 'Store Owner'), ('admin', 'Admin')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='passwordresetcode',
            index=models.Index(fields=['user', 'is_used'], name='idx_reset_user_used'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='idx_user_is_active'),
        ),
    ]
