# Generated by Django 6.0.6 on 2026-06-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_order_payment_status_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
