# Generated by Django 6.0.6 on 2026-06-09 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_menuitem_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='store_owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'store_owner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
