# Generated by Django 4.2.13 on 2026-06-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_menuitem_store_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Acceptance'), ('received', 'Order Received'), ('preparing', 'Preparing'), ('ready_for_pickup', 'Ready for Pick-Up'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Acceptance'), ('received', 'Order Received'), ('preparing', 'Preparing'), ('ready_for_pickup', 'Ready for Pick-Up'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
