# Generated by Django 4.2.13 on 2026-06-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_alter_order_status_alter_orderstatushistory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notifications_last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
