# Generated by Django 4.2.13 on 2026-06-10 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_migrate_store_owners_to_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreOwnerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejection_reason', models.TextField(blank=True)),
                ('resubmit_count', models.IntegerField(default=0)),
                ('last_resubmit_at', models.DateTimeField(blank=True, null=True)),
                ('is_deactivated', models.BooleanField(default=False)),
                ('deactivation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Store Owner Status',
                'verbose_name_plural': 'Store Owner Statuses',
            },
        ),
    ]
