# Generated by Django 4.2.13 on 2026-06-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_migrate_store_owner_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprofile',
            name='dti_permit',
            field=models.ImageField(blank=True, null=True, upload_to='dti_permits/'),
        ),
    ]
