# Generated by Django 4.2.13 on 2026-06-10 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_copy_dti_permits_to_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='available_days',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='available_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='available_to',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='featured_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='low_stock_threshold',
            field=models.IntegerField(default=5),
        ),
        migrations.CreateModel(
            name='ItemVariation',
            fields=[
                ('variation_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_available', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='customer.menuitem')),
            ],
            options={
                'verbose_name': 'Item Variation',
                'verbose_name_plural': 'Item Variations',
            },
        ),
    ]
