# Generated by Django 4.2.13 on 2026-06-10 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_menu_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='store_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Acceptance'), ('store_accepted', 'Accepted by Store'), ('store_rejected', 'Rejected by Store'), ('preparing', 'Preparing'), ('ready_for_pickup', 'Ready for Pick-Up'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Acceptance'), ('store_accepted', 'Accepted by Store'), ('store_rejected', 'Rejected by Store'), ('preparing', 'Preparing'), ('ready_for_pickup', 'Ready for Pick-Up'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
