# Generated by Django 4.2.13 on 2026-06-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_migrate_store_profiles_to_stores'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='faculty_id_image',
            field=models.ImageField(blank=True, null=True, upload_to='faculty_ids/'),
        ),
    ]
