# Generated by Django 4.2.13 on 2026-06-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_user_faculty_id_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='parent_order_group',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
