# Generated by Django 4.2.13 on 2026-06-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0028_user_deactivated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='store',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
