# Generated by Django 4.2.13 on 2026-06-16 12:32

from django.db import migrations


def backfill_store_approvals(apps, schema_editor):
    Store = apps.get_model('customer', 'Store')
    Store.objects.filter(owner__is_active=True).update(is_approved=True)


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0029_store_contact_person_store_is_approved'),
    ]

    operations = [
        migrations.RunPython(backfill_store_approvals, migrations.RunPython.noop),
    ]
