# Generated by Django 4.2.13 on 2026-06-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0030_backfill_existing_store_approvals'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='closed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
