from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView
from . import views

urlpatterns = [
    path('api/auth/register/', views.register, name='register'),
    path('api/auth/register/store/', views.store_register, name='store-register'),
    path('api/auth/login/', views.login, name='login'),
    path('api/auth/logout/', views.logout, name='logout'),
    path('api/auth/forgot-password/', views.forgot_password, name='forgot-password'),
    path('api/auth/reset-password/', views.reset_password, name='reset-password'),
    path('api/auth/token/refresh/', TokenRefreshView.as_view(), name='token-refresh'),
    path('api/auth/me/', views.me, name='me'),
    path('api/menu/', views.menu_list, name='menu-list'),
    path('api/menu/<int:item_id>/', views.menu_item_detail, name='menu-item-detail'),
    path('api/cart/', views.get_cart, name='cart'),
    path('api/cart/add/', views.add_to_cart, name='cart-add'),
    path('api/cart/item/<uuid:cart_item_id>/', views.update_cart_item, name='cart-item-update'),
    path('api/cart/clear/', views.clear_cart, name='cart-clear'),
    path('api/orders/', views.my_orders, name='my-orders'),
    path('api/orders/place/', views.place_order, name='place-order'),
    path('api/orders/<uuid:order_id>/', views.order_detail, name='order-detail'),
    path('api/orders/<uuid:order_id>/track/', views.track_order, name='track-order'),
    path('api/feedback/', views.submit_feedback, name='submit-feedback'),
    path('api/seed/admin/', views.seed_admin, name='seed-admin'),
    path('api/seed/menu/', views.seed_menu, name='seed-menu'),
    path('api/seed/ids/', views.seed_valid_ids, name='seed-ids'),
    path('api/admin/orders/<uuid:order_id>/status/', views.force_order_status, name='force-order-status'),

    path('api/store/orders/', views.store_orders, name='store-orders'),
    path('api/store/orders/<uuid:order_id>/status/', views.store_update_order_status, name='store-order-status'),
    path('api/store/menu/', views.store_all_menu_items, name='store-menu-list'),
    path('api/store/menu/create/', views.store_create_menu_item, name='store-menu-create'),
    path('api/store/menu/<int:item_id>/', views.store_update_menu_item, name='store-menu-update'),
    path('api/store/menu/<int:item_id>/delete/', views.store_delete_menu_item, name='store-menu-delete'),

    path('api/kaon-admin/stats/', views.admin_stats, name='admin-stats'),
    path('api/kaon-admin/users/', views.admin_users, name='admin-users'),
    path('api/kaon-admin/users/<uuid:user_id>/approve/', views.admin_approve_user, name='admin-approve-user'),
    path('api/kaon-admin/users/<uuid:user_id>/reject/', views.admin_reject_user, name='admin-reject-user'),
    path('api/kaon-admin/users/<uuid:user_id>/delete/', views.admin_delete_user, name='admin-user-delete'),
    path('api/kaon-admin/orders/', views.admin_all_orders, name='admin-orders'),
    path('api/kaon-admin/feedback/', views.admin_feedback, name='admin-feedback'),
    path('api/kaon-admin/menu/', views.admin_all_menu_items, name='admin-menu'),

    path('', views.landing_page, name='landing'),
    path('login/', views.login_page, name='login-page'),
    path('forgot-password/', views.forgot_password_page, name='forgot-password-page'),
    path('reset-password/', views.reset_password_page, name='reset-password-page'),
    path('register/', views.register_page, name='register-page'),
    path('register/store/', views.store_register_page, name='store-register-page'),
    path('logout/', views.logout_page, name='logout-page'),
    path('dashboard/', views.store_dashboard_page, name='store-dashboard-page'),
    path('kaon-admin/', views.admin_dashboard_page, name='admin-dashboard-page'),
    path('menu/', views.menu_page, name='menu-page'),
    path('cart/', views.cart_page, name='cart-page'),
    path('orders/', views.my_orders_page, name='my-orders-page'),
    path('order/<uuid:order_id>/', views.order_confirmation_page, name='order-confirmation-page'),
    path('order/<uuid:order_id>/track/', views.order_tracking_page, name='order-tracking-page'),
    path('order/<uuid:order_id>/feedback/', views.feedback_page, name='feedback-page'),
]
