from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView
from . import views

urlpatterns = [
    path('api/auth/register/', views.register, name='register'),
    path('api/auth/register/store/', views.store_register, name='store-register'),
    path('api/auth/login/', views.login, name='login'),
    path('api/auth/logout/', views.logout, name='logout'),
    path('api/auth/forgot-password/', views.forgot_password, name='forgot-password'),
    path('api/auth/reset-password/', views.reset_password, name='reset-password'),
    path('api/auth/token/refresh/', TokenRefreshView.as_view(), name='token-refresh'),
    path('api/auth/me/', views.me, name='me'),
    path('api/menu/', views.menu_list, name='menu-list'),
    path('api/menu/<int:item_id>/', views.menu_item_detail, name='menu-item-detail'),
    path('api/cart/', views.get_cart, name='cart'),
    path('api/cart/add/', views.add_to_cart, name='cart-add'),
    path('api/cart/item/<uuid:cart_item_id>/', views.update_cart_item, name='cart-item-update'),
    path('api/cart/clear/', views.clear_cart, name='cart-clear'),
    path('api/orders/', views.my_orders, name='my-orders'),
    path('api/orders/place/', views.place_order, name='place-order'),
    path('api/orders/repeat/', views.repeat_last_order, name='repeat-order'),
    path('api/orders/<uuid:order_id>/', views.order_detail, name='order-detail'),
    path('api/orders/<uuid:order_id>/track/', views.track_order, name='track-order'),
    path('api/feedback/', views.submit_feedback, name='submit-feedback'),
    path('api/seed/admin/', views.seed_admin, name='seed-admin'),
    path('api/seed/menu/', views.seed_menu, name='seed-menu'),
    path('api/seed/ids/', views.seed_valid_ids, name='seed-ids'),
    path('api/admin/orders/<uuid:order_id>/status/', views.force_order_status, name='force-order-status'),

    path('api/store/analytics/summary/', views.store_analytics_summary, name='store-analytics-summary'),
    path('api/store/analytics/revenue/', views.store_analytics_revenue, name='store-analytics-revenue'),
    path('api/store/analytics/top-items/', views.store_analytics_top_items, name='store-analytics-top-items'),
    path('api/store/analytics/peak-hours/', views.store_analytics_peak_hours, name='store-analytics-peak-hours'),
    path('api/store/profile/', views.store_profile, name='store-profile'),
    path('api/store/profile/toggle-open/', views.store_toggle_open, name='store-toggle-open'),
    path('api/store/manage/', views.store_manage, name='store-manage'),
    path('api/store/manage/<int:store_id>/', views.store_manage_detail, name='store-manage-detail'),
    path('api/store/manage/<int:store_id>/switch/', views.store_switch, name='store-switch'),
    path('api/store/profile/resubmit-permit/', views.store_resubmit_permit, name='store-resubmit-permit'),
    path('api/store/promotions/discounts/', views.store_discounts, name='store-discounts'),
    path('api/store/promotions/discounts/<int:discount_id>/', views.store_discount_detail, name='store-discount-detail'),
    path('api/store/promotions/bundles/', views.store_bundles, name='store-bundles'),
    path('api/store/promotions/bundles/<int:bundle_id>/', views.store_bundle_detail, name='store-bundle-detail'),
    path('api/orders/apply-discount/', views.apply_discount, name='apply-discount'),
    path('api/store/orders/', views.store_orders, name='store-orders'),
    path('api/store/orders/<uuid:order_id>/status/', views.store_update_order_status, name='store-order-status'),
    path('api/store/orders/<uuid:order_id>/eta/', views.store_set_eta, name='store-order-eta'),
    path('api/store/menu/', views.store_all_menu_items, name='store-menu-list'),
    path('api/store/menu/create/', views.store_create_menu_item, name='store-menu-create'),
    path('api/store/menu/<int:item_id>/', views.store_update_menu_item, name='store-menu-update'),
    path('api/store/menu/<int:item_id>/delete/', views.store_delete_menu_item, name='store-menu-delete'),
    path('api/store/menu/<int:item_id>/feature/', views.store_toggle_featured, name='store-menu-feature'),
    path('api/store/menu/<int:item_id>/duplicate/', views.store_duplicate_menu_item, name='store-menu-duplicate'),
    path('api/store/menu/<int:item_id>/variations/', views.store_item_variations, name='store-menu-variations'),
    path('api/store/menu/bulk/update/', views.store_bulk_menu_update, name='store-menu-bulk-update'),
    path('api/store/feedback/', views.store_feedback, name='store-feedback'),
    path('api/store/notifications/', views.store_notifications, name='store-notifications'),
    path('api/store/notifications/read/', views.store_notifications_read, name='store-notifications-read'),

    path('api/kaon-admin/stats/', views.admin_stats, name='admin-stats'),
    path('api/kaon-admin/users/', views.admin_users, name='admin-users'),
    path('api/kaon-admin/users/<uuid:user_id>/approve/', views.admin_approve_user, name='admin-approve-user'),
    path('api/kaon-admin/users/<uuid:user_id>/reject/', views.admin_reject_user, name='admin-reject-user'),
    path('api/kaon-admin/users/<uuid:user_id>/delete/', views.admin_delete_user, name='admin-user-delete'),
    path('api/kaon-admin/orders/', views.admin_all_orders, name='admin-orders'),
    path('api/kaon-admin/feedback/', views.admin_feedback, name='admin-feedback'),
    path('api/kaon-admin/menu/', views.admin_all_menu_items, name='admin-menu'),
    path('api/kaon-admin/stores/', views.admin_stores, name='admin-stores-list'),
    path('api/kaon-admin/stores/<uuid:user_id>/deactivate/', views.admin_deactivate_store, name='admin-store-deactivate'),
    path('api/kaon-admin/stores/<uuid:user_id>/activate/', views.admin_activate_store, name='admin-store-activate'),

    path('', views.landing_page, name='landing'),
    path('login/', views.login_page, name='login-page'),
    path('forgot-password/', views.forgot_password_page, name='forgot-password-page'),
    path('reset-password/', views.reset_password_page, name='reset-password-page'),
    path('register/', views.register_page, name='register-page'),
    path('register/store/', views.store_register_page, name='store-register-page'),
    path('logout/', views.logout_page, name='logout-page'),
    path('dashboard/', views.store_dashboard_page, name='store-dashboard-page'),
    path('kaon-admin/', views.admin_dashboard_page, name='admin-dashboard-page'),
    path('menu/', views.menu_page, name='menu-page'),
    path('cart/', views.cart_page, name='cart-page'),
    path('orders/', views.my_orders_page, name='my-orders-page'),
    path('order/<uuid:order_id>/', views.order_confirmation_page, name='order-confirmation-page'),
    path('order/<uuid:order_id>/track/', views.order_tracking_page, name='order-tracking-page'),
    path('order/<uuid:order_id>/feedback/', views.feedback_page, name='feedback-page'),
]
